spring:
  redis:
    host: localhost
    password:
    database: 0
    port: 6379

#配置成自己电脑上webapp路径，发布时可改为服务器上路径
webapp:
  path: E:\java_related_file\workspace\idea_workspace\myproject\ssotest\ssotest\sso-admin\src\main\webapp
