server:
  port: 5000

spring:
  mvc:
    view:
      prefix: /WEB-INF/test/
      suffix: .jsp
  thymeleaf:
    cache: false
    enabled: false
  profiles:
    active: local


#shiro配置文件路径
shiro:
  configLocation: classpath:shiro/ehcache-shiro.xml

sso:
  loginUrl:
  otherSystem: false